$mainMod = SUPER

bind = $mainMod, RETURN, exec, foot
bind = $mainMod, W, exec, librewolf
bind = $mainMod, TAB, exec, foot -e ranger
bind = $mainMod SHIFT, C, killactive,
bind = $mainMod SHIFT, Q, exit,
#bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, exec, wofi --show drun
bind = $mainMod, E, exec, eject -T
#bind = $mainMod, R, pseudo, # dwindle
bind = $mainMod, M, togglesplit, # dwindle
#bind = $mainMod, N, exec, fnottctl dismiss
bind = $mainMod, R, exec, wofi --term='foot -H' --show=run
bind = , Print, exec, grim -l 9  $HOME/HDD/shots/$(date +'%F_%H%M%S'.png)
bind = $mainMod, Print, exec, grim -l 9 -g "$(slurp)" $HOME/HDD/shots/$(date +'%F_%H%M%S'.png)
bind = $mainMod, F, fullscreen

# media
bind= , XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind= , XF86AudioRaiseVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86audiostop, exec, playerctl stop

# Move focus with mainMod + arrow keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod ALT, l, resizeactive, 10 0
bind = $mainMod ALT, k, resizeactive, 0 -10
bind = $mainMod ALT, j, resizeactive, 0 10
bind = $mainMod ALT, h, resizeactive, -10 0

bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d
bind = $mainMod SHIFT, h, movewindow, l