layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace waybar

windowrule = opacity 0.88 override 0.88 override, match:class librewolf
windowrule = opacity 0.88 override 0.88 override, match:class emacs
windowrule = opacity 0.88 override 0.88 override, match:class ^(?i)(obsidian|md\.obsidian\.Obsidian)$

layerrule = blur on, match:class librewolf
layerrule = blur on, match:class emacs