decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    screen_shader = ~/.config/hypr/shaders/grayscale.glsl
    active_opacity = 0.88
    inactive_opacity = 0.88
    fullscreen_opacity = 1

    # Rounding borders, default 10
    rounding = 14

   shadow {
   enabled = true
   color = 0xee1c1e1e
   range = 1
   scale = 1.0
   }

    blur {
    enabled = true
    size = 14
    passes = 3       # 2–3 is a good start
    new_optimizations = true
    ignore_opacity = false
    xray = false

    enabled = true
    size = 14
    passes = 5
    noise = 0.003
    contrast = 0.8
    brightness = 0.50
    vibrancy = 0.2
    }
}