exec-once = hyprpaper
exec-once = /usr/bin/gentoo-pipewire-launcher
exec-once = openrazer-daemon -r
exec-once = /usr/libexec/xdg-desktop-portal-hyprland
exec-once = /usr/libexec/xdg-desktop-portal
exec-once = /usr/lib/polkit-1/polkitd
#exec-once = mpd
exec-once = waybar
exec-once = fnott
exec-once = hyprctl setcursor Borealis-cursors 24

source = ~/.config/hypr/io/monitors.conf
source = ~/.config/hypr/io/input.conf

source = ~/.config/hypr/settings/env.conf

source = ~/.config/hypr/settings/bindings.conf
source = ~/.config/hypr/settings/layout.conf
source = ~/.config/hypr/settings/rules.conf

source = ~/.config/hypr/theme/general.conf
source = ~/.config/hypr/theme/decoration.conf
source = ~/.config/hypr/theme/animations.conf
source = ~/.config/hypr/misc.conf



#gestures {
#    # See https://wiki.hyprland.org/Configuring/Variables/ for more
#    workspace_swipe = off
#}